apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    appc: client
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: web-port
    protocol: TCP
  selector:
    appc: client
